// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const rootDir = dirname(fileURLToPath(import.meta.url));
config({ path: resolve(rootDir, ".env") });

const databaseUrl = process.env["DATABASE_URL"];
/** Migrate/introspect: conexão direta (Neon DIRECT_URL ou DATABASE_URL sem pooler). */
const migrateUrl =
	process.env["DIRECT_URL"]?.trim() ||
	process.env["MIGRATE_DATABASE_URL"]?.trim() ||
	databaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrateUrl,
  },
});
